FROM python:3.9

EXPOSE 8501

WORKDIR /streamlit-app

COPY ./streamlit-app/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./streamlit-app .
COPY ./resources ./resources

CMD streamlit run App.py