apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "{{ .Release.Name }}"
  namespace: seldon
spec:
  name: "{{ .Release.Name }}"
  annotations:
    project_name: project_name
    deployment_version: v1
  predictors:
    - name: "{{ .Values.model_a.name }}"
      replicas: 1
      traffic: 50
      componentSpecs:
        - spec:
            containers:
              - image: "{{ .Values.model_a.image.name }}:{{ .Values.model_a.image.version }}"
                imagePullPolicy: IfNotPresent
                name: "{{ .Values.model_a.name }}"
                env:
                  - name: VERSION
                    value: "A"
            terminationGracePeriodSeconds: 1
      graph:
        children: []
        endpoint:
          type: REST
        name: "{{ .Values.model_a.name }}"
        type: MODEL
    - name: "{{ .Values.model_b.name }}"
      replicas: 1
      traffic: 50
      componentSpecs:
      - spec:
          containers:
            - image: "{{ .Values.model_b.image.name }}:{{ .Values.model_b.image.version }}"
              imagePullPolicy: IfNotPresent
              name: "{{ .Values.model_b.name }}"
              env:
                - name: VERSION
                  value: "B"
          terminationGracePeriodSeconds: 1
      graph:
        children: [ ]
        endpoint:
          type: REST
        name: "{{ .Values.model_b.name }}"
        type: MODEL
