apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: {{ .Values.app.image }}:{{ .Values.app.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: streamlit
              containerPort: 8501
