apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: streamlit-app
  ports:
    - name: http
      port: 8501
      targetPort: streamlit